/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoAlgoritmo;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sreales4
 */
public class CrearPersonas extends javax.swing.JFrame {

    Empleado e1 = new Empleado("Cristian", "suarez", 1140876403, "2019-12-11", "calle 54 32", "cristian@gmail.com", "masculino", 2, "soltero", "profesional", "ingeniero sistemas", "soporte", "2019-12-11", "2019-12-11", "indefinido", "salud total", "Sura", "porvenir", "compensiones");
    Empleado e2 = new Empleado("Andres", "martinez", 1540854605, "2019-04-11", "calle 23 65", "andres@gmail.com", "masculino", 2, "soltero", "tecnico", "ingeniero ambiental", "comercial", "2019-05-12", "2019-10-09", "obra y labor", "coosalud", "arlsani", "cesantis", "porloir");
    
    ArrayList<Empleado> Empleados = new ArrayList<Empleado>();

    Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
    int indice_empleado;

    /**
     * Creates new form CrearPersonas
     */
    public CrearPersonas() {
        initComponents();
        Empleados.add(e1);
        Empleados.add(e2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_identificacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbx_genero = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        cbx_estadoCivil = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        spn_nHijos = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        txt_profesion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_nivelEducativo = new javax.swing.JTextField();
        JDC_FNac = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txt_cargo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbx_tipoContrato = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        txt_eps = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_arl = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_cesantias = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_pension = new javax.swing.JTextField();
        JDC_FIng = new com.toedter.calendar.JDateChooser();
        JDC_FSalida = new com.toedter.calendar.JDateChooser();
        btn_guardar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatosPersonas = new javax.swing.JTable();
        ActualizarLista = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txt_nombre1 = new javax.swing.JTextField();
        txt_apellido1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_identificacion1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_direccion1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txt_correo1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        cbx_genero1 = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        cbx_estadoCivil1 = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        spn_nHijos1 = new javax.swing.JSpinner();
        jLabel29 = new javax.swing.JLabel();
        txt_profesion1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txt_nivelEducativo1 = new javax.swing.JTextField();
        JDC_FNac1 = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        txt_cargo1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        cbx_tipoContrato1 = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        txt_eps1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txt_arl1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txt_cesantias1 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txt_pension1 = new javax.swing.JTextField();
        JDC_FIng1 = new com.toedter.calendar.JDateChooser();
        JDC_FSalida1 = new com.toedter.calendar.JDateChooser();
        jPanel8 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_guardar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador recursos humanos");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));

        jLabel1.setText("Nombre:");

        txt_nombre.setName("txt_nombre"); // NOI18N

        txt_apellido.setName("txt_apellido"); // NOI18N

        jLabel2.setText("Apellido:");

        jLabel3.setText("Identificacion:");

        txt_identificacion.setName("txt_identificacion"); // NOI18N
        txt_identificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_identificacionKeyTyped(evt);
            }
        });

        jLabel4.setText("Fecha Nacimiento:");

        jLabel5.setText("Direccion:");

        txt_direccion.setName("txt_direccion"); // NOI18N

        jLabel6.setText("Correo:");

        txt_correo.setName("txt_correo"); // NOI18N

        jLabel7.setText("Genero:");

        cbx_genero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino", "Otro" }));
        cbx_genero.setName("cbx_genero"); // NOI18N

        jLabel8.setText("Estado Civil:");

        cbx_estadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Soltero", "Casado", "Divorciado", "Viudo", "Union Libre" }));
        cbx_estadoCivil.setName("cbx_estadoCivil"); // NOI18N

        jLabel9.setText("# Hijos:");

        spn_nHijos.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spn_nHijos.setName("spn_nHijos"); // NOI18N

        jLabel10.setText("Profesion:");

        txt_profesion.setName("txt_profesion"); // NOI18N

        jLabel11.setText("Nivel Educativo:");

        txt_nivelEducativo.setName("txt_nivelEducativo"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(txt_identificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(txt_nombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(txt_apellido)
                            .addComponent(jLabel4)
                            .addComponent(JDC_FNac, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                        .addGap(77, 77, 77))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_correo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(cbx_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(cbx_estadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(spn_nHijos, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)))
                            .addComponent(txt_profesion)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10))
                                .addGap(119, 119, 119))
                            .addComponent(txt_direccion))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txt_nivelEducativo, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 37, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JDC_FNac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_identificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_estadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spn_nHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_profesion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nivelEducativo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Empleado"));

        jLabel12.setText("Cargo:");

        txt_cargo.setName("txt_cargo"); // NOI18N

        jLabel13.setText("Fecha Ingreso:");

        jLabel14.setText("Fecha Salida:");

        jLabel15.setText("Tipo de Contrato:");

        cbx_tipoContrato.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Prestacion de Servicios", "Obra Labor", "Termino Fijo", "Indefinido" }));
        cbx_tipoContrato.setName("cbx_tipoContrato"); // NOI18N

        jLabel16.setText("EPS:");

        txt_eps.setName("txt_eps"); // NOI18N

        jLabel17.setText("ARL:");

        txt_arl.setName("txt_arl"); // NOI18N

        jLabel18.setText("Cesantias:");

        txt_cesantias.setName("txt_cesantias"); // NOI18N

        jLabel19.setText("Pension:");

        txt_pension.setName("txt_pension"); // NOI18N

        JDC_FSalida.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JDC_FIng, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(JDC_FSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15)
                            .addComponent(cbx_tipoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 233, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(306, 306, 306)
                                .addComponent(jLabel17))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_eps, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                    .addComponent(jLabel18)
                                    .addComponent(txt_cesantias))
                                .addGap(113, 113, 113)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(txt_arl, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_pension, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(102, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JDC_FIng, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JDC_FSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_tipoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_eps, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_arl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cesantias, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pension, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btn_guardar.setText("Guardar");
        btn_guardar.setName("btn_guardar"); // NOI18N
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear", jPanel3);

        jScrollPane1.setBorder(new javax.swing.border.MatteBorder(null));

        tablaDatosPersonas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaDatosPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Identificacion", "Fecha de Nac.", "Dirrecion", "Correo", "Genero", "Estado Civil", "# Hijos", "Profesion", "Nivel educativo", "Cargo", "Fecha Ingreso", "Fecha Salida", "Tipo de contrato", "EPS", "ARL", "Cesantias", "Pension"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaDatosPersonas);

        ActualizarLista.setText("Listar");
        ActualizarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1297, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ActualizarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ActualizarLista, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Listar", jPanel4);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));

        jLabel20.setText("Nombre:");

        txt_nombre1.setName("txt_nombre"); // NOI18N

        txt_apellido1.setName("txt_apellido"); // NOI18N

        jLabel21.setText("Apellido:");

        jLabel22.setText("Identificacion:");

        txt_identificacion1.setName("txt_identificacion"); // NOI18N
        txt_identificacion1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_identificacion1KeyTyped(evt);
            }
        });

        jLabel23.setText("Fecha Nacimiento:");

        jLabel24.setText("Direccion:");

        txt_direccion1.setName("txt_direccion"); // NOI18N
        txt_direccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direccion1ActionPerformed(evt);
            }
        });

        jLabel25.setText("Correo:");

        txt_correo1.setName("txt_correo"); // NOI18N

        jLabel26.setText("Genero:");

        cbx_genero1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino", "Otro" }));
        cbx_genero1.setName("cbx_genero"); // NOI18N

        jLabel27.setText("Estado Civil:");

        cbx_estadoCivil1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Soltero", "Casado", "Divorciado", "Viudo", "Union Libre" }));
        cbx_estadoCivil1.setName("cbx_estadoCivil"); // NOI18N

        jLabel28.setText("# Hijos:");

        spn_nHijos1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spn_nHijos1.setName("spn_nHijos"); // NOI18N

        jLabel29.setText("Profesion:");

        txt_profesion1.setName("txt_profesion"); // NOI18N

        jLabel30.setText("Nivel Educativo:");

        txt_nivelEducativo1.setName("txt_nivelEducativo"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(txt_identificacion1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(txt_nombre1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel21)
                            .addComponent(txt_apellido1)
                            .addComponent(jLabel23)
                            .addComponent(JDC_FNac1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                        .addGap(77, 77, 77))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_nivelEducativo1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(cbx_genero1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(cbx_estadoCivil1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(spn_nHijos1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_direccion1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_correo1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_profesion1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JDC_FNac1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_identificacion1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_direccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_correo1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addGap(11, 11, 11)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_genero1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_estadoCivil1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spn_nHijos1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_profesion1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nivelEducativo1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Empleado"));

        jLabel31.setText("Cargo:");

        txt_cargo1.setName("txt_cargo"); // NOI18N

        jLabel32.setText("Fecha Ingreso:");

        jLabel33.setText("Fecha Salida:");

        jLabel34.setText("Tipo de Contrato:");

        cbx_tipoContrato1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Prestacion de Servicios", "Obra Labor", "Termino Fijo", "Indefinido" }));
        cbx_tipoContrato1.setName("cbx_tipoContrato"); // NOI18N

        jLabel35.setText("EPS:");

        txt_eps1.setName("txt_eps"); // NOI18N

        jLabel36.setText("ARL:");

        txt_arl1.setName("txt_arl"); // NOI18N

        jLabel37.setText("Cesantias:");

        txt_cesantias1.setName("txt_cesantias"); // NOI18N

        jLabel38.setText("Pension:");

        txt_pension1.setName("txt_pension"); // NOI18N

        JDC_FSalida1.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_cargo1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JDC_FIng1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(JDC_FSalida1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel31)
                    .addComponent(jLabel34)
                    .addComponent(cbx_tipoContrato1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_eps1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                .addComponent(jLabel37)
                                .addComponent(txt_cesantias1))
                            .addComponent(jLabel35))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel38)
                            .addComponent(txt_arl1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_pension1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cargo1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JDC_FIng1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JDC_FSalida1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_tipoContrato1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_eps1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_arl1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cesantias1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pension1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar "));

        jLabel39.setText("Identificación: ");

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_guardar1.setText("Guardar");
        btn_guardar1.setName("btn_guardar"); // NOI18N
        btn_guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_buscar)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_guardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Actualizar", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActualizarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarListaActionPerformed
        //Para cuando exista información almacenada previa al guardar nuevos datos
        mostrar();
    }//GEN-LAST:event_ActualizarListaActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed

        if (txt_identificacion.getText().isEmpty()) {

            JOptionPane.showMessageDialog(rootPane, "Por favor, verificar el campo de identificación", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (txt_nombre.getText().isEmpty() || txt_apellido.getText().isEmpty() || cbx_genero.getSelectedItem().toString().isEmpty() || txt_direccion.getText().isEmpty() || JDC_FNac.getDate() == null || txt_correo.getText().isEmpty()
                || cbx_estadoCivil.getSelectedItem().toString().isEmpty() || txt_nivelEducativo.getText().isEmpty() || txt_profesion.getText().isEmpty() || txt_cargo.getText().isEmpty() || JDC_FIng.getDate() == null || JDC_FSalida.getDate() == null || cbx_tipoContrato.getSelectedItem().toString().isEmpty()
                || txt_eps.getText().isEmpty() || txt_arl.getText().isEmpty() || txt_cesantias.getText().isEmpty() || txt_pension.getText().isEmpty()) {

            JOptionPane.showMessageDialog(rootPane, "Por favor llene todos los campos", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!pattern.matcher(txt_correo.getText()).find()) {
            JOptionPane.showMessageDialog(rootPane, "El correo ingresado no es valido", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            String nombre = txt_nombre.getText();
            String apellido = txt_apellido.getText();
            int id = Integer.parseInt(txt_identificacion.getText());
            String nacimiento = JDC_FNac.getDate().toString();
            String direccion = txt_direccion.getText();
            String email = txt_correo.getText();
            String genero = cbx_genero.getSelectedItem().toString();
            int nhijos = Integer.parseInt(spn_nHijos.getValue().toString());
            String ecivil = cbx_estadoCivil.getSelectedItem().toString();
            String neduc = txt_nivelEducativo.getText();
            String profesion = txt_profesion.getText();
            String cargo = txt_cargo.getText();
            String fing = JDC_FIng.getDate().toString();
            String fsal = JDC_FSalida.getDate().toString();
            String contrato = cbx_tipoContrato.getSelectedItem().toString();
            String EPS = txt_eps.getText();
            String ARL = txt_arl.getText();
            String cesantias = txt_cesantias.getText();
            String pension = txt_pension.getText();

            Empleado e = new Empleado(nombre, apellido, id, nacimiento, direccion, email, genero, nhijos, ecivil, neduc, profesion, cargo, fing, fsal, contrato, EPS, ARL, cesantias, pension);

            Empleados.add(e);

            JOptionPane.showMessageDialog(rootPane, "Los datos se han guardado exitosamente.", "Exito", JOptionPane.INFORMATION_MESSAGE);

            //tal vez lo utilice después
            /*
            no borrar util otra forma de llenar la tabla con un for y agregando lo siguiente
            Object [] fila = new Object [nCol]
            fila[0] = e.getId(); ir colocando la información en la tabla
            DefaultTableModel modelo =(DefaultTableModel) tablaDatosPersonas.getModel();
            tablaDatosPersonas.setModel(modelo);
            for (int i = 0; i < Empleados.size(); i++) {
                /*fila[i] = e.getNombre();
                fila[i] = e.getApellido();
                fila[i] = e.getId();
                fila[i] = e.getNacimiento();
                fila[i] = e.getDireccion();
                fila[i] = e.getEmail();
                fila[i] = e.getGenero();
                fila[i] = e.getEstadoCivil();
                fila[i] = e.getNHijos();
                fila[i] = e.getProfesion();
                fila[i] = e.getNivelEducativo();
                fila[i] = e.getCargo();
                fila[i] = e.getFechaDeIngreso();
                fila[i] = e.getFechaDeSalida();
                fila[i] = e.getTipoContrato();
                fila[i] = e.getEPS();
                fila[i] = e.getARL();
                fila[i] = e.getCesantias();
                fila[i] = e.getPension();
                modelo.addRow(new Object[]{Empleados.get(i).getNombre(), Empleados.get(i).getApellido(), Empleados.get(i).getId(), Empleados.get(i).getNacimiento(), Empleados.get(i).getDireccion(), Empleados.get(i).getEmail(), Empleados.get(i).getGenero(), Empleados.get(i).getEstadoCivil(), Empleados.get(i).getNHijos(), Empleados.get(i).getProfesion(), Empleados.get(i).getNivelEducativo(), Empleados.get(i).getCargo(), Empleados.get(i).getFechaDeIngreso(), Empleados.get(i).getFechaDeSalida(), Empleados.get(i).getTipoContrato(), Empleados.get(i).getEPS(), Empleados.get(i).getARL(), Empleados.get(i).getCesantias(), Empleados.get(i).getPension()});
            }
             */
            //new Object[]{Empleados.get(i).getNombre(), Empleados.get(i).getApellido(), Empleados.get(i).getId(), Empleados.get(i).getNacimiento(), Empleados.get(i).getDireccion(), Empleados.get(i).getEmail(), Empleados.get(i).getGenero(), Empleados.get(i).getEstadoCivil(), Empleados.get(i).getNHijos(), Empleados.get(i).getProfesion(), Empleados.get(i).getNivelEducativo(), Empleados.get(i).getCargo(), Empleados.get(i).getFechaDeIngreso(), Empleados.get(i).getFechaDeSalida(), Empleados.get(i).getTipoContrato(), Empleados.get(i).getEPS(), Empleados.get(i).getARL(), Empleados.get(i).getCesantias(), Empleados.get(i).getPension()}
            //actualizar
            mostrar();
            //limpiar campos
            txt_nombre.setText("");
            txt_apellido.setText("");
            txt_identificacion.setText("");
            JDC_FNac.setDate(null);
            JDC_FIng.setDate(null);
            JDC_FSalida.setDate(null);
            txt_direccion.setText("");
            txt_correo.setText("");
            spn_nHijos.setValue(0);
            txt_nivelEducativo.setText("");
            txt_profesion.setText("");
            txt_cargo.setText("");
            txt_eps.setText("");
            txt_arl.setText("");
            txt_cesantias.setText("");
            txt_pension.setText("");

        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void txt_identificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_identificacionKeyTyped
        char car = evt.getKeyChar();
        if (Character.isDigit(car)) {

        } else {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txt_identificacionKeyTyped

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed

        if (txt_buscar.getText().isEmpty()) {

            JOptionPane.showMessageDialog(rootPane, "Por favor, verificar el campo de identificación está vacío", "Warning", JOptionPane.WARNING_MESSAGE);

        } else {
            int idBuscar = Integer.parseInt(txt_buscar.getText());
            int existe = 0;
            for (int i = 0; i < Empleados.size(); i++) {
                if (idBuscar == Empleados.get(i).getId()) {
                    existe = 1;
                    indice_empleado = i;
                }
            }

            if (existe == 1) {
                System.out.println("si existe el numero");
                txt_nombre1.setText(Empleados.get(indice_empleado).getNombre());
                txt_apellido1.setText(Empleados.get(indice_empleado).getApellido());
                txt_identificacion1.setText(Integer.toString(Empleados.get(indice_empleado).getId()));
                JDC_FNac1.setDate(null);
                JDC_FIng1.setDate(null);
                JDC_FSalida1.setDate(null);
                txt_direccion1.setText(Empleados.get(indice_empleado).getDireccion());
                txt_correo1.setText(Empleados.get(indice_empleado).getEmail());
                spn_nHijos1.setValue(Empleados.get(indice_empleado).getNHijos());
                txt_nivelEducativo1.setText(Empleados.get(indice_empleado).getNivelEducativo());
                txt_profesion1.setText(Empleados.get(indice_empleado).getProfesion());
                txt_cargo1.setText(Empleados.get(indice_empleado).getCargo());
                txt_eps1.setText(Empleados.get(indice_empleado).getEPS());
                txt_arl1.setText(Empleados.get(indice_empleado).getARL());
                txt_cesantias1.setText(Empleados.get(indice_empleado).getCesantias());
                txt_pension1.setText(Empleados.get(indice_empleado).getPension());
                System.out.println("este es el id" + indice_empleado);

            } else {
                JOptionPane.showMessageDialog(rootPane, "La identificacion ingresada no existe", "Warning", JOptionPane.WARNING_MESSAGE);
                txt_nombre1.setText("");
                txt_apellido1.setText("");
                txt_identificacion1.setText("");
                JDC_FNac1.setDate(null);
                JDC_FIng1.setDate(null);
                JDC_FSalida1.setDate(null);
                txt_direccion1.setText("");
                txt_correo1.setText("");
                spn_nHijos1.setValue(0);
                txt_nivelEducativo1.setText("");
                txt_profesion1.setText("");
                txt_cargo1.setText("");
                txt_eps1.setText("");
                txt_arl1.setText("");
                txt_cesantias1.setText("");
                txt_pension1.setText("");
            }
        }

    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar1ActionPerformed

        if (txt_identificacion1.getText().isEmpty()) {

            JOptionPane.showMessageDialog(rootPane, "Por favor, verificar el campo de identificación", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (txt_nombre1.getText().isEmpty() || txt_apellido1.getText().isEmpty() || cbx_genero1.getSelectedItem().toString().isEmpty() || txt_direccion1.getText().isEmpty() || JDC_FNac1.getDate() == null || txt_correo1.getText().isEmpty()
                || cbx_estadoCivil1.getSelectedItem().toString().isEmpty() || txt_nivelEducativo1.getText().isEmpty() || txt_profesion1.getText().isEmpty() || txt_cargo1.getText().isEmpty() || JDC_FIng1.getDate() == null || JDC_FSalida1.getDate() == null || cbx_tipoContrato1.getSelectedItem().toString().isEmpty()
                || txt_eps1.getText().isEmpty() || txt_arl1.getText().isEmpty() || txt_cesantias1.getText().isEmpty() || txt_pension1.getText().isEmpty()) {

            JOptionPane.showMessageDialog(rootPane, "Por favor llene todos los campos", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!pattern.matcher(txt_correo1.getText()).find()) {
            JOptionPane.showMessageDialog(rootPane, "El correo ingresado no es valido", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            //actualiza valores 
            Empleados.get(indice_empleado).setNombre(txt_nombre1.getText());
            Empleados.get(indice_empleado).setApellido(txt_apellido1.getText());
            Empleados.get(indice_empleado).setId(Integer.parseInt(txt_identificacion1.getText()));
            Empleados.get(indice_empleado).setNacimiento(JDC_FNac1.getDate().toString());
            Empleados.get(indice_empleado).setDireccion(txt_direccion1.getText());
            Empleados.get(indice_empleado).setEmail(txt_correo1.getText());
            Empleados.get(indice_empleado).setGenero(cbx_genero1.getSelectedItem().toString());
            Empleados.get(indice_empleado).setEstadoCivil(cbx_estadoCivil1.getSelectedItem().toString());
            Empleados.get(indice_empleado).setNHijos(Integer.parseInt(spn_nHijos1.getValue().toString()));
            Empleados.get(indice_empleado).setProfesion(txt_profesion1.getText());
            Empleados.get(indice_empleado).setNivelEducativo(txt_nivelEducativo1.getText());
            Empleados.get(indice_empleado).setCargo(txt_cargo1.getText());
            Empleados.get(indice_empleado).setFechaDeIngreso(JDC_FIng1.getDate().toString());
            Empleados.get(indice_empleado).setFechaDeSalida(JDC_FSalida1.getDate().toString());
            Empleados.get(indice_empleado).setTipoContrato(cbx_tipoContrato1.getSelectedItem().toString());
            Empleados.get(indice_empleado).setEPS(txt_eps1.getText());
            Empleados.get(indice_empleado).setARL(txt_arl1.getText());
            Empleados.get(indice_empleado).setCesantias(txt_cesantias1.getText());
            Empleados.get(indice_empleado).setPension(txt_pension1.getText());
            JOptionPane.showMessageDialog(rootPane, "Los datos se han guardado exitosamente.", "Exito", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btn_guardar1ActionPerformed

    private void txt_direccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direccion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccion1ActionPerformed

    private void txt_identificacion1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_identificacion1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_identificacion1KeyTyped

    public void mostrar() {

        Object matriz[][] = new Object[Empleados.size()][19];

        for (int i = 0; i < Empleados.size(); i++) {

            matriz[i][0] = Empleados.get(i).getNombre();
            matriz[i][1] = Empleados.get(i).getApellido();
            matriz[i][2] = Empleados.get(i).getId();
            matriz[i][3] = Empleados.get(i).getNacimiento();
            matriz[i][4] = Empleados.get(i).getDireccion();
            matriz[i][5] = Empleados.get(i).getEmail();
            matriz[i][6] = Empleados.get(i).getGenero();
            matriz[i][7] = Empleados.get(i).getEstadoCivil();
            matriz[i][8] = Empleados.get(i).getNHijos();
            matriz[i][9] = Empleados.get(i).getProfesion();
            matriz[i][10] = Empleados.get(i).getNivelEducativo();
            matriz[i][11] = Empleados.get(i).getCargo();
            matriz[i][12] = Empleados.get(i).getFechaDeIngreso();
            matriz[i][13] = Empleados.get(i).getFechaDeSalida();
            matriz[i][14] = Empleados.get(i).getTipoContrato();
            matriz[i][15] = Empleados.get(i).getEPS();
            matriz[i][16] = Empleados.get(i).getARL();
            matriz[i][17] = Empleados.get(i).getCesantias();
            matriz[i][18] = Empleados.get(i).getPension();
        }

        tablaDatosPersonas.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "Nombre", "Apellido", "Identificacion", "Fecha de Nac.", "Dirrecion", "Correo", "Genero", "Estado Civil", "# Hijos", "Profesion", "Nivel educativo", "Cargo", "Fecha Ingreso", "Fecha Salida", "Tipo de contrato", "EPS", "ARL", "Cesantias", "Pension"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }

        });

    }

    public void buscar() {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearPersonas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarLista;
    private com.toedter.calendar.JDateChooser JDC_FIng;
    private com.toedter.calendar.JDateChooser JDC_FIng1;
    private com.toedter.calendar.JDateChooser JDC_FNac;
    private com.toedter.calendar.JDateChooser JDC_FNac1;
    private com.toedter.calendar.JDateChooser JDC_FSalida;
    private com.toedter.calendar.JDateChooser JDC_FSalida1;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_guardar1;
    private javax.swing.JComboBox cbx_estadoCivil;
    private javax.swing.JComboBox cbx_estadoCivil1;
    private javax.swing.JComboBox cbx_genero;
    private javax.swing.JComboBox cbx_genero1;
    private javax.swing.JComboBox cbx_tipoContrato;
    private javax.swing.JComboBox cbx_tipoContrato1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner spn_nHijos;
    private javax.swing.JSpinner spn_nHijos1;
    private javax.swing.JTable tablaDatosPersonas;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_apellido1;
    private javax.swing.JTextField txt_arl;
    private javax.swing.JTextField txt_arl1;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_cargo;
    private javax.swing.JTextField txt_cargo1;
    private javax.swing.JTextField txt_cesantias;
    private javax.swing.JTextField txt_cesantias1;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_correo1;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_direccion1;
    private javax.swing.JTextField txt_eps;
    private javax.swing.JTextField txt_eps1;
    private javax.swing.JTextField txt_identificacion;
    private javax.swing.JTextField txt_identificacion1;
    private javax.swing.JTextField txt_nivelEducativo;
    private javax.swing.JTextField txt_nivelEducativo1;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombre1;
    private javax.swing.JTextField txt_pension;
    private javax.swing.JTextField txt_pension1;
    private javax.swing.JTextField txt_profesion;
    private javax.swing.JTextField txt_profesion1;
    // End of variables declaration//GEN-END:variables
}
